version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3309:3306
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=auth
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: