services:
  mysql:
    image: mysql:8.0
    ports:
      - "3309:3306" # Map host port 3309 to container port 3306 (MySQL default)
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: auth
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
